---
abstract: 'Magnet URI scheme'
author:
  - 'Breno G. de Oliveira <garu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-magnet
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0.88
  URI: 0
  URI::QueryParam: 0
  parent: 0
version: 0.01
